name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm ci
      - name: Build Docker images
        run: docker compose build
      - name: Run API tests
        run: pytest --cov=. --cov-report=xml -x
      - name: Run node tests
        run: npm test
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml
